#!/usr/bin/env node
/**
 * Step (e) of `build.mjs`: package the Python agent into a wheel and drop it
 * under `assets/agent/` so the deployed Worker carries its own agent release
 * (spec `2026-09-24-single-stack-selfhost-and-remote-update.md` §2.1).
 *
 *   assets/agent/comfyfed-<version>-py3-none-any.whl
 *   assets/agent/release.json   {"version","filename","sha256"}
 *
 * `core/agent_release.ts` reads `release.json` through the ASSETS binding
 * and, when the bundled version is newer than the published `agent_latest`
 * setting, signs it with the platform key and publishes it -- so a push to
 * `main` is a full agent release, with no operator upload step.
 *
 * Inputs (all read from the repo, nothing generated by Python tooling --
 * Workers Builds' container has Node but no guaranteed Python):
 *   - `agent/comfyfed_agent/**\/*.py`  (no `__pycache__`)
 *   - `agent/comfyfed_agent/__init__.py`'s `__version__`, which MUST equal
 *     `pyproject.toml`'s `[project] version` (both are bumped together; a
 *     mismatch aborts the build rather than shipping a wheel whose filename
 *     disagrees with what the code reports in `hello`).
 *   - `pyproject.toml`'s `requires-python`, `[project] dependencies`,
 *     `[project.scripts]` and `[project.optional-dependencies] mcp`.
 */

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { sha256Hex } from "./build-lib.mjs";
import { buildWheel, pythonDunderVersion, tomlString, tomlStringArray } from "./wheel-lib.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CLOUD_DIR = path.join(HERE, "..");
const REPO_DIR = path.join(CLOUD_DIR, "..");
const AGENT_PACKAGE = "comfyfed_agent";
const AGENT_SRC_DIR = path.join(REPO_DIR, "agent", AGENT_PACKAGE);
const PYPROJECT_PATH = path.join(REPO_DIR, "pyproject.toml");
const DIST_NAME = "comfyfed";
const RELEASE_FILENAME = "release.json";

function log(msg) {
  console.log(`[build] ${msg}`);
}

/** Every `.py` under `dir`, as `Map<"comfyfed_agent/<rel>", Buffer>`. */
async function collectPackageFiles(dir, prefix) {
  const files = new Map();
  async function walk(current, rel) {
    const entries = await readdir(current, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === "__pycache__") continue;
      const full = path.join(current, entry.name);
      const relPath = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        await walk(full, relPath);
      } else if (entry.isFile() && entry.name.endsWith(".py")) {
        files.set(`${prefix}/${relPath}`, await readFile(full));
      }
    }
  }
  await walk(dir, "");
  if (!files.has(`${prefix}/__init__.py`)) {
    throw new Error(`${dir} has no __init__.py -- not a package?`);
  }
  return files;
}

/** `[project.scripts]` entries whose target lives in the agent package. */
function agentConsoleScripts(pyproject) {
  const scripts = {};
  const re = /^\s*([A-Za-z0-9_.-]+)\s*=\s*"([^"]+)"/gm;
  const sectionStart = pyproject.indexOf("[project.scripts]");
  if (sectionStart < 0) throw new Error("pyproject.toml: no [project.scripts] section");
  const rest = pyproject.slice(sectionStart + "[project.scripts]".length);
  const next = rest.search(/^\[[^\]]+\]\s*$/m);
  const body = next < 0 ? rest : rest.slice(0, next);
  for (const m of body.matchAll(re)) {
    const [, name, target] = m;
    if (target.startsWith(`${AGENT_PACKAGE}.`)) scripts[name] = target;
  }
  if (Object.keys(scripts).length === 0) throw new Error("pyproject.toml: no agent console scripts found");
  return scripts;
}

/**
 * Reads everything the wheel needs and returns `{ filename, bytes, version,
 * sha256 }`. Exported so a Node-side caller (or a future test with a real
 * filesystem) can build without writing.
 */
export async function buildAgentWheel({ agentSrcDir = AGENT_SRC_DIR, pyprojectPath = PYPROJECT_PATH } = {}) {
  const pyproject = await readFile(pyprojectPath, "utf8");
  const initSource = await readFile(path.join(agentSrcDir, "__init__.py"), "utf8");

  const version = pythonDunderVersion(initSource);
  const projectVersion = tomlString(pyproject, "project", "version");
  if (!version) throw new Error(`${agentSrcDir}/__init__.py: no __version__`);
  if (version !== projectVersion) {
    throw new Error(
      `agent __version__ (${version}) != pyproject.toml version (${projectVersion}); bump both together.`
    );
  }
  const requiresPython = tomlString(pyproject, "project", "requires-python");
  if (!requiresPython) throw new Error("pyproject.toml: no requires-python");
  const requiresDist = tomlStringArray(pyproject, "project", "dependencies");
  if (!requiresDist || requiresDist.length === 0) {
    throw new Error("pyproject.toml: [project] dependencies is missing or empty");
  }
  const mcpExtra = tomlStringArray(pyproject, "project.optional-dependencies", "mcp") ?? [];
  const license = tomlString(pyproject, "project", "license");

  const files = await collectPackageFiles(agentSrcDir, AGENT_PACKAGE);
  const wheel = buildWheel({
    name: DIST_NAME,
    version,
    files,
    topLevel: [AGENT_PACKAGE],
    consoleScripts: agentConsoleScripts(pyproject),
    requiresPython,
    requiresDist,
    extras: mcpExtra.length ? { mcp: mcpExtra } : {},
    summary: "ComfyFed worker agent",
    license: license ?? undefined,
  });
  return { filename: wheel.filename, bytes: wheel.bytes, version, sha256: sha256Hex(wheel.bytes), fileCount: files.size };
}

/** Writes the wheel + release.json into `outDir`, replacing whatever was there. */
export async function writeAgentRelease(outDir, options = {}) {
  const built = await buildAgentWheel(options);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, built.filename), built.bytes);
  const release = { version: built.version, filename: built.filename, sha256: built.sha256 };
  await writeFile(path.join(outDir, RELEASE_FILENAME), JSON.stringify(release, null, 2) + "\n");
  log(
    `agent wheel: ${built.filename} (${built.fileCount} files, ${(built.bytes.length / 1024).toFixed(1)} KB, sha256 ${built.sha256}) -> ${path.relative(CLOUD_DIR, outDir)}/`
  );
  return release;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const outDir = process.argv[2] ?? path.join(CLOUD_DIR, "assets", "agent");
  writeAgentRelease(outDir).catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
